# permissions for end users to view domains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: domain-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: domain-operator
    app.kubernetes.io/part-of: domain-operator
    app.kubernetes.io/managed-by: kustomize
  name: domain-viewer-role
rules:
  - apiGroups:
      - domain.platform.com
    resources:
      - domains
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - domain.platform.com
    resources:
      - domains/status
    verbs:
      - get
