# permissions for end users to edit teams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: team-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: team-operator
    app.kubernetes.io/part-of: team-operator
    app.kubernetes.io/managed-by: kustomize
  name: team-editor-role
rules:
- apiGroups:
  - platform.example.com
  resources:
  - teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.example.com
  resources:
  - teams/status
  verbs:
  - get
